
export const PREDEFINED_SKILLS = [
    "JavaScript",
    "React",
    "TypeScript",
    "Python",
    "Java",
    "HTML/CSS",
    "Design",
    "Marketing",
    "Vendas",
    "Gestão de Projetos",
    "Redes Sociais",
    "Edição de Vídeo",
    "Fotografia",
    "Ensino",
    "Redação",
    "Tradução",
    "Psicologia",
    "Enfermagem",
    "Direito",
    "Contabilidade",
    "Assistência Social",
    "Meio Ambiente",
    "Agricultura",
    "Logística",
    "Culinária",
    "Artesanato",
    "Nutrição",
    "Comunicação",
    "Saúde",
    "Excel",
    "PowerPoint",
    "Word",
    "Photoshop",
] as const;

export const PREDEFINED_SOFT_SKILLS = [
    "Liderança",
    "Empatia",
    "Proatividade",
    "Comunicação",
    "Trabalho em Equipe",
    "Criatividade",
    "Organização",
    "Flexibilidade",
    "Resolução de Problemas",
    "Pensamento Crítico",
    "Gestão de Tempo",
    "Adaptabilidade",
    "Paciência",
    "Escuta Ativa",
    "Colaboração",
    "Responsabilidade",
    "Comprometimento",
    "Iniciativa",
    "Resiliência",
    "Ética",
] as const;

export type Skill = typeof PREDEFINED_SKILLS[number];
export type SoftSkill = typeof PREDEFINED_SOFT_SKILLS[number];
