
export const PREDEFINED_SKILLS = [
    "Informática",
    "Design",
    "Marketing",
    "Vendas",
    "Gestão de Projetos",
    "Redes Sociais",
    "Edição de Vídeo",
    "Fotografia",
    "Ensino",
    "Redação",
    "Tradução",
    "Psicologia",
    "Enfermagem",
    "Direito",
    "Contabilidade",
    "Assistência Social",
    "Meio Ambiente",
    "Agricultura",
    "Logística",
    "Culinária",
    "Artesanato",
    "Nutrição",
    "Comunicação",
    "Saúde",
    "Cuidado com crianças",
    "Cuidado com idosos",
    "Cuidado com animais",
    "Apoio a pessoas com deficiência",
] as const;

export type Skill = typeof PREDEFINED_SKILLS[number];
